[package]
name = "os-memlock"
version = "0.1.0"
edition = "2024"
description = "Unsafe thin wrappers around OS memory locking syscalls (mlock/munlock/madvise)"
license = "MIT OR Apache-2.0"
license-file = "../../LICENSE-MIT"
license-file-apache = "../../LICENSE-APACHE"
readme = "README.md"

[dependencies]
libc = "0.2"
